CREATE TABLE USER_INFO (
  `ID` bigint NOT NULL AUTO_INCREMENT COMMENT 'PK',
  `USER_NO` varchar(20) DEFAULT NULL COMMENT '用户账号',
  `USER_NAME` varchar(20) DEFAULT NULL COMMENT '用户名称',
  `PASSWORD` varchar(50) DEFAULT NULL COMMENT '密码',
  `PHONE` char(11) DEFAULT NULL COMMENT '电话',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='用户信息表';


CREATE TABLE ORDER_INFO (
  `ID` bigint NOT NULL AUTO_INCREMENT COMMENT 'PK',
  `USER_ID` bigint DEFAULT NULL COMMENT 'user_info.id',
  `ORDER_NO` char(25) DEFAULT NULL COMMENT '订单编号',
  `TOTAL_AMOUNT` decimal(10,2) DEFAULT NULL COMMENT '总金额',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='订单信息表';


CREATE TABLE ORDER_DETAILS (
  `ID` bigint NOT NULL AUTO_INCREMENT COMMENT 'PK',
  `GOOD_ID` bigint DEFAULT NULL COMMENT 'goods.id',
  `ORDER_ID` bigint DEFAULT NULL COMMENT 'order.id',
  `ORIGIN_PRICE` decimal(10,2) DEFAULT NULL COMMENT '原价',
  `DISCOUNTED_PRICE` decimal(10,2) DEFAULT NULL COMMENT '折后价格',
  `DISCOUNT` float DEFAULT NULL COMMENT '折扣',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='订单明细表';


CREATE TABLE GOODS (
  `ID` bigint NOT NULL AUTO_INCREMENT COMMENT 'PK',
  `TYPE` char(1) DEFAULT NULL COMMENT '商品分类',
  `PRICE` decimal(10,2) DEFAULT NULL COMMENT '商品原价',
  `DISPLAY_NAME` varchar(255) DEFAULT NULL COMMENT '商品名称',
  `LEFT_COUNTS` int DEFAULT NULL COMMENT '剩余数量',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='商品表';


